### ISSUE TITLE
audio still runs when a module is not scheduled

### ISSUE THREAD

**Issue by doug-doug** [ianperrin/MMM-ModuleScheduler#12]
Trying to use MMM-ModuleScheduler to queue MMM-YouTube-API to play a specific video at a specific time.
To test out my project, I set the video to "loop=true" and schedule it to run for ten minutes and to start about ten minutes after I started MM.
The video begins playback when MM starts, not ten minutes after it starts.  The video does appear and disappear on schedule.
If this is not really a "bug", please regard it as an enhancement request (suggestions on how to do what I want in the interim are gratefully appreciated).

**Comment by ianperrin** [comment]
Hi @doug-doug 

It’s not possible for MMM-ModuleScheduler to affect the behaviour of the modules it hides/shows.

However, it is possible for a modules to ‘react’ to being shown/hidden.  

To achieve this you could ask the developer of MMM-YouTube-API to implement/subclass the [suspend](https://github.com/MichMich/MagicMirror/tree/develop/modules#suspend) and [resume](https://github.com/MichMich/MagicMirror/tree/develop/modules#resume) methods so that the video playback is paused/restarted.

Hope this helps
